MODEL:
  TYPE: aff 
  NAME: aff_mini_1_4th
  DROP_PATH_RATE: 0.0
  AFF:
    DEPTHS: [ 2, 2, 6, 2]
    NUM_HEADS: [ 2, 4, 8, 16 ]
    MLP_RATIO: 2.
    EMBED_DIM: [32,128,256,384]
    CLUSTER_SIZE: 8
    NBHD_SIZE: [48,48,48,49]
    ALPHA: 4.0
    DS_RATE: 0.25
DATA:
  DATASET: imagenet 
  IMG_SIZE: 224
  BATCH_SIZE: 1024 
TRAIN:
  EPOCHS: 300
  BASE_LR: 5e-4
  MIN_LR: 5e-6
  WARMUP_LR: 5e-7
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0
