MODEL:
  TYPE: aff 
  NAME: aff_small_1_4th 
  DROP_PATH_RATE: 0.3
  AFF:
    DEPTHS: [3,4,18,2]
    NUM_HEADS: [3,6,12,24]
    MLP_RATIO: 3.
    EMBED_DIM: [96,192,384,768]
    CLUSTER_SIZE: 8
    NBHD_SIZE: [48,48,48,49] 
    LAYER_SCALE: 1e-5 # turned off if 0.0
    ALPHA: 4.0
    DS_RATE: 0.25
DATA:
  DATASET: imagenet 
  IMG_SIZE: 224
  BATCH_SIZE: 256 
TRAIN:
  EPOCHS: 300
  BASE_LR: 5e-4
  MIN_LR: 5e-6
  WARMUP_LR: 5e-7
AUG:
  MIXUP: 0.8
  CUTMIX: 1.0
